config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # , controllers: {
  # registrations: 'users/registrations',
  # checking if user signs up
  # sessions: 'users/sessions'
  # checking if user is logged into a session
  # }

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "home#index"

  resources :trips do
    resources :groups, only: [:new, :create]
    resources :goals, only: [:new, :create]
    resources :itineraries do
      resources :cities, only: [:new, :create]
    end
  end
  
  resources :groups do
    resources :group_members, only: [:new, :create]
  end

  resources :group_members
  resources :goals, only: [:edit, :update]
  
  resources :charts, only: [] do
    collection  do
      get 'new_users', to: 'charts#new_users'
      get 'trip_start', to: 'charts#trip_start'
      get 'cities', to: 'charts#cities'
      # get 'new_goals', to: 'charts#new_goals'
    end
  end

  get '/dashboard', to: 'dashboard#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
  before_save :downcase_fields
  validates :city, :region, :country, presence: true
  validates_uniqueness_of :city, :scope => [:region, :country], :case_sensitive => false
  # works for city only, region and country are case sensitive
  # validate :unique_city


  has_many :itineraries

  def downcase_fields
    self.city.downcase!
    self.region.downcase!
    self.country.downcase!
  end

  # def unique_city
  #   if City.find_by(city: :city)
  #     validates_uniqueness_of :region, case_sensitive => false
  #     p 'test'
  #   end
  # end
end

app/models/goal.rb
class Goal < ApplicationRecord
  validates :user_id, :trip_id, :total_goal, :current_amount, :deadline, presence: true
  validates_uniqueness_of :trip_id, scope: :user_id
  belongs_to :trip
end

app/models/group.rb
class Group < ApplicationRecord
  validates :nickname, presence: true
  belongs_to :admin, class_name: 'User'
  belongs_to :creator, class_name: 'User' 
  has_many :group_members
  has_many :trips
end

app/models/group_member.rb
class GroupMember < ApplicationRecord
  validates :group_id, :user_id, presence: true
  validates_uniqueness_of :group_id, scope: :user_id
  belongs_to :group
end

app/models/itinerary.rb
class Itinerary < ApplicationRecord
  validates :start_date, :end_date, presence: true
  validates_uniqueness_of :city_id, scope: :trip_id
  belongs_to :trip
  belongs_to :city
end

app/models/trip.rb
class Trip < ApplicationRecord
  validates :nickname, :total_cost, :funds_deadline, :trip_start_date, :trip_end_date, presence: true
 
  belongs_to :group, optional: true
  belongs_to :creator, class_name: 'User'
  has_many :itineraries
  has_many :goals
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :trips
  has_many :groups
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :authenticate_user!
  skip_before_action :verify_authenticity_token, only: [:destroy]
  
  def index
    @myTrips = []

    @myGroups = GroupMember.where(user_id: current_user.id)
    @myGroups.each do |g|
      trip = Trip.find_by(group_id: g.group_id)
      if trip.present?
        @myTrips.push(trip)
      end
    end

    trips = Trip.where(creator_id: current_user.id)
    if trips.present?
      trips.each do |t|
        unless @myTrips.include?(t)
          @myTrips.push(t)
        end
      end
    end

  end
end

app/controllers/goals_controller.rb
class GoalsController < ApplicationController
  respond_to :html, :json
  
  # custom method for chartkick chart
  def new_goals
    # render json: Goal.group_by_day(:created_at).count
    # render json: Goal.where(user_id: :user_id, trip_id: :trip_id)
  end

  def new
    @trip = Trip.find(params[:trip_id])
    @trip_goal = Goal.new
    @form_resource = [@trip, @trip_goal]
  end

  def create
    trip = Trip.find(params[:trip_id])
    Goal.create(goal_params.merge(
      user_id: current_user.id,
       trip_id: trip.id, 
       deadline: trip.funds_deadline
       ))
    redirect_to trip
  end

  def edit
    @trip_goal = Goal.find(params[:id])
    @form_resource = @trip_goal
    @trip = Trip.find(@trip_goal.trip_id)
  end

  def update
    @trip_goal = Goal.find(params[:id])
    @trip_goal.update(goal_params)
    trip = Trip.find(@trip_goal.trip_id)
    redirect_to trip
  end

  private

  def goal_params
    params.require(:goal).permit(
      :total_goal, 
      :current_amount
      )
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  # def index
  #   @users = User.all
  #   respond_to do |f|
  #     f.html
  #   end
  # end

end

app/controllers/trips_controller.rb
class TripsController < ApplicationController
  before_action :authenticate_user!
  skip_before_action :verify_authenticity_token, only: [:destroy]
  
  def index
    @trips = Trip.all
  end

  def new
    @trip = Trip.new
    myGroup = GroupMember.where(user_id: current_user.id)
    @groups = myGroup.map do |g|
      [g.group.nickname, g.group.id]
    end
  end

  def create
    trip = Trip.create(trip_params.merge(creator_id: current_user.id))
    flash[:success] = "Trip has been successfully created"
    redirect_to dashboard_path
  end

  def show
    @trip = Trip.find(params[:id])
    find_trip = Itinerary.where(trip_id: @trip.id)
    @itinerary = []
    if find_trip
      find_trip.each do |t|
        @city = City.find(t.city_id)
        @itinerary.push(t)
      end
    end
    @members = []
    if @trip.group_id
      current_group = Group.find(@trip.group.id)
      current_members = GroupMember.where(group_id: current_group.id)
      current_members.each do |member|
        @members.push(User.find(member.user_id))
      end
    end
  end

  def edit
    @trip = Trip.find(params[:id])
    myGroup = GroupMember.where(user_id: current_user.id)
    @groups = myGroup.map do |g|
      [g.group.nickname,g.group.id]
    end
  end

  def update
    trip = Trip.find(params[:id])
    if trip.group_id != params[:group_id]
      trip.goals.ids.each do |t|
        Goal.destroy(t)
      end
    end
    trip.update(trip_params)
    redirect_to trip
  end

  def destroy
    Trip.destroy(params[:id])
    render json: {
      status: "success",
     message: "Trip was successfully deleted"
   }
  end

  private

  def trip_params
    params.require(:trip).permit(
      :nickname, 
      :total_cost, 
      :funds_deadline, 
      :trip_start_date, 
      :trip_end_date, 
      :group_id
    )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def custom_bootstrap_flash
    flash_messages = []
    flash.each do |type, message|
      type = 'success' if type == 'notice'
      type = 'error'   if type == 'alert'
      text = "<script>toastr.#{type}('#{message}');</script>"
      flash_messages << text.html_safe if message
    end
    flash_messages.join("\n").html_safe
  end
end

app/helpers/charts_helper.rb
module ChartsHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/goals_helper.rb
module GoalsHelper
end

app/helpers/group_members_helper.rb
module GroupMembersHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/itineraries_helper.rb
module ItinerariesHelper
end

app/helpers/trips_helper.rb
module TripsHelper
end

app/views/dashboard/index.html.erb
<div class="row max-width bg-img">
  <div class="col-12 center no-padding">
    <%= image_tag image_path("map-single.jpg"), alt: "map image", class: "hero-img opacity-secondary" %>
  </div>
</div>

<div class="row max-width no-margin mt-2">
  
  <div class="col-3 dash-col dash-split">
    
    <div class="row">
      <div class="col-12 no-padding">
        <h3 class="center thirdary-color">My Groups</h3>
      </div>
    </div>

    <div class="row mt-3 mb-3">
      <div class="col-12 no-padding">
        <%= link_to "New Group", new_group_path, class: "btn btn-info btn-block" %>
      </div>
    </div>

    <div class="row">
      <div class="col-12 no-padding">
        <ul class="no-padding">
          <% if @myGroups.nil? %>
            <h4>You have no groups yet - create a group or ask a friend for an invite!</h4>
          <% else %>
            <% @myGroups.each do |group| %>
              <li class="link center dash-group"><%= link_to group.group.nickname, group.group %></li>
            <% end %>
          <% end %>
        </ul>
      </div>
    </div>

  </div>


  <div class="col-8 dash-col">
    
    <div class="row">
      <div class="col-12">
        <h3 class="center thirdary-color">My Trips</h3>
      </div>
    </div>

    <div class="row mt-3 mb-3">
      <div class="col-12">
        <%= link_to "New Trip", new_trip_path, class: "btn btn-info btn-block" %>
      </div>
    </div>

    <div class="row">
      <div class="col-12 no-padding">

        <% if @myTrips.nil? %>

          <h4>You have no trips yet - create a trip or ask a friend for an invite!</h4>

        <% else %>

          <table class="table table-striped table-hover">
            <thead>
              <tr>
                <th scope="col">Trip</th>
                <th scope="col">Group</th>
                <th scope="col">Dates</th>
              </tr>
            </thead>
            <tbody>
              <% @myTrips.each do |t| %> 
                <tr>
                  <th scope="row" class="link"><%= link_to t.nickname, t %></th>
                  <td>
                    <% if t.group_id.nil? %>
                      N/A
                    <% else %>
                      <%= link_to Group.find(t.group_id).nickname, Group.find(t.group_id), class: "dash-link" %>
                    <% end %>
                  </td>
                  <td><%= t.trip_start_date.strftime("%m/%d") %> - <%= t.trip_end_date.strftime("%m/%d/%Y") %></td>
                </tr>
              <% end %>
            </tbody>
          </table>

        <% end %>

      </div>
    </div>

  </div>

</div>