config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # , controllers: {
  # registrations: 'users/registrations',
  # checking if user signs up
  # sessions: 'users/sessions'
  # checking if user is logged into a session
  # }

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "home#index"

  resources :trips do
    resources :groups, only: [:new, :create]
    resources :goals, only: [:new, :create]
    resources :itineraries do
      resources :cities, only: [:new, :create]
    end
  end
  
  resources :groups do
    resources :group_members, only: [:new, :create]
  end

  resources :group_members
  resources :goals, only: [:edit, :update]
  
  resources :charts, only: [] do
    collection  do
      get 'new_users', to: 'charts#new_users'
      get 'trip_start', to: 'charts#trip_start'
      get 'cities', to: 'charts#cities'
      # get 'new_goals', to: 'charts#new_goals'
    end
  end

  get '/dashboard', to: 'dashboard#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
  before_save :downcase_fields
  validates :city, :region, :country, presence: true
  validates_uniqueness_of :city, :scope => [:region, :country], :case_sensitive => false
  # works for city only, region and country are case sensitive
  # validate :unique_city


  has_many :itineraries

  def downcase_fields
    self.city.downcase!
    self.region.downcase!
    self.country.downcase!
  end

  # def unique_city
  #   if City.find_by(city: :city)
  #     validates_uniqueness_of :region, case_sensitive => false
  #     p 'test'
  #   end
  # end
end

app/models/goal.rb
class Goal < ApplicationRecord
  validates :user_id, :trip_id, :total_goal, :current_amount, :deadline, presence: true
  validates_uniqueness_of :trip_id, scope: :user_id
  belongs_to :trip
end

app/models/group.rb
class Group < ApplicationRecord
  validates :nickname, presence: true
  belongs_to :admin, class_name: 'User'
  belongs_to :creator, class_name: 'User' 
  has_many :group_members
  has_many :trips
end

app/models/group_member.rb
class GroupMember < ApplicationRecord
  validates :group_id, :user_id, presence: true
  validates_uniqueness_of :group_id, scope: :user_id
  belongs_to :group
end

app/models/itinerary.rb
class Itinerary < ApplicationRecord
  validates :start_date, :end_date, presence: true
  validates_uniqueness_of :city_id, scope: :trip_id
  belongs_to :trip
  belongs_to :city
end

app/models/trip.rb
class Trip < ApplicationRecord
  validates :nickname, :total_cost, :funds_deadline, :trip_start_date, :trip_end_date, presence: true
 
  belongs_to :group, optional: true
  belongs_to :creator, class_name: 'User'
  has_many :itineraries
  has_many :goals
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :trips
  has_many :groups
end

app/controllers/charts_controller.rb
class ChartsController < ApplicationController
  def new_users
    render json: User.group_by_day(:created_at).count
  end

  def trip_start
    render json: Trip.group(:trip_start_date).count
  end

  def cities
    cities = City.group(:country).count
    results = {}
    cities.keys.each do |key|
      results[key.titleize] = cities[key]
    end
    render json: results
  end

  def new_goals
    # render json: [
    #   { name: "Current".
    #     data: Goal.group(:current).count
    #   }
    # ]
    
    render json: Goal.group(:goal).count

    # render json: [
    #   {name: "Current", data: Goal.group(:current)},
    #   {name: "Goal", data: Goal.group(:goal)}
    # ]

  end
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  before_action :authenticate_user!
  skip_before_action :verify_authenticity_token, only: [:destroy]
  

  def new
    City.new
  end

  def create
    City.create(city_params)
  end

  private
  def city_params
    params.require(:itinerary).permit(
      :city, 
      :region, 
      :country
      )
  end

end

app/controllers/goals_controller.rb
class GoalsController < ApplicationController
  respond_to :html, :json
  
  # custom method for chartkick chart
  def new_goals
    # render json: Goal.group_by_day(:created_at).count
    # render json: Goal.where(user_id: :user_id, trip_id: :trip_id)
  end

  def new
    @trip = Trip.find(params[:trip_id])
    @trip_goal = Goal.new
    @form_resource = [@trip, @trip_goal]
  end

  def create
    trip = Trip.find(params[:trip_id])
    Goal.create(goal_params.merge(
      user_id: current_user.id,
       trip_id: trip.id, 
       deadline: trip.funds_deadline
       ))
    redirect_to trip
  end

  def edit
    @trip_goal = Goal.find(params[:id])
    @form_resource = @trip_goal
    @trip = Trip.find(@trip_goal.trip_id)
  end

  def update
    @trip_goal = Goal.find(params[:id])
    @trip_goal.update(goal_params)
    trip = Trip.find(@trip_goal.trip_id)
    redirect_to trip
  end

  private

  def goal_params
    params.require(:goal).permit(
      :total_goal, 
      :current_amount
      )
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  # def index
  #   @users = User.all
  #   respond_to do |f|
  #     f.html
  #   end
  # end

end

app/controllers/trips_controller.rb
class TripsController < ApplicationController
  before_action :authenticate_user!
  skip_before_action :verify_authenticity_token, only: [:destroy]
  
  def index
    @trips = Trip.all
  end

  def new
    @trip = Trip.new
    myGroup = GroupMember.where(user_id: current_user.id)
    @groups = myGroup.map do |g|
      [g.group.nickname, g.group.id]
    end
  end

  def create
    trip = Trip.create(trip_params.merge(creator_id: current_user.id))
    flash[:success] = "Trip has been successfully created"
    redirect_to dashboard_path
  end

  def show
    @trip = Trip.find(params[:id])
    find_trip = Itinerary.where(trip_id: @trip.id)
    @itinerary = []
    if find_trip
      find_trip.each do |t|
        @city = City.find(t.city_id)
        @itinerary.push(t)
      end
    end
    @members = []
    if @trip.group_id
      current_group = Group.find(@trip.group.id)
      current_members = GroupMember.where(group_id: current_group.id)
      current_members.each do |member|
        @members.push(User.find(member.user_id))
      end
    end
  end

  def edit
    @trip = Trip.find(params[:id])
    myGroup = GroupMember.where(user_id: current_user.id)
    @groups = myGroup.map do |g|
      [g.group.nickname,g.group.id]
    end
  end

  def update
    trip = Trip.find(params[:id])
    if trip.group_id != params[:group_id]
      trip.goals.ids.each do |t|
        Goal.destroy(t)
      end
    end
    trip.update(trip_params)
    redirect_to trip
  end

  def destroy
    Trip.destroy(params[:id])
    render json: {
      status: "success",
     message: "Trip was successfully deleted"
   }
  end

  private

  def trip_params
    params.require(:trip).permit(
      :nickname, 
      :total_cost, 
      :funds_deadline, 
      :trip_start_date, 
      :trip_end_date, 
      :group_id
    )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def custom_bootstrap_flash
    flash_messages = []
    flash.each do |type, message|
      type = 'success' if type == 'notice'
      type = 'error'   if type == 'alert'
      text = "<script>toastr.#{type}('#{message}');</script>"
      flash_messages << text.html_safe if message
    end
    flash_messages.join("\n").html_safe
  end
end

app/helpers/charts_helper.rb
module ChartsHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/goals_helper.rb
module GoalsHelper
end

app/helpers/group_members_helper.rb
module GroupMembersHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/itineraries_helper.rb
module ItinerariesHelper
end

app/helpers/trips_helper.rb
module TripsHelper
end

app/views/goals/_form.html.erb
<%= form_for @form_resource do |f| %>

  <div class="form-group">
    <%= f.label :total_goal %>
    <%= f.number_field :total_goal, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :current_amount %>
    <%= f.number_field :current_amount, class: "form-control" %>
  </div>

  <br />

  <div class="form-group">
    <%= f.submit "Save Goal", class: "btn btn-outline-success btn-block" %>
  </div>
<% end %>

app/views/goals/edit.html.erb
<div class="row max-width">
  <div class="col-12 center">
    <h3>Edit member goal</h3>
  </div>
</div>

<div class="row max-width mt-3">
  <div class="col-6 auto-margin">
    <%= render "form" %>
    <br>
    <div  class="links">
        <%= link_to "Cancel", @trip, "class": "btn btn-outline-danger btn-sm btn-block mb-3" %>
    </div>
  </div>
</div>

app/views/goals/new.html.erb
<div class="row max-width">
  <div class="col-12 center">
    <h3>Add a new member goal</h3>
  </div>
</div>

<div class="row max-width mt-3">
  <div class="col-6 auto-margin">
    <%= render "form" %>
    <br>
    <div  class="links">
        <%= link_to "Cancel", @trip, "class": "btn btn-outline-danger btn-sm btn-block mb-3" %>
    </div>
  </div>
</div>

app/views/trips/_form.html.erb
<%= form_for @trip do |f| %>
  <div class="form-group">
    <%= f.label :nickname %>
    <%= f.text_field :nickname, class: "form-control" %>
  </div>
  
  <div class="form-group">
    <%= f.label :total_cost %>
    <%= f.number_field :total_cost, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :funds_deadline %>
    <%= f.date_field :funds_deadline, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :trip_start_date %>
    <%= f.date_field :trip_start_date, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :trip_end_date %>
    <%= f.date_field :trip_end_date, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :group_id %>
    <%= f.select :group_id, options_for_select(@groups, @trip.group_id), :include_blank => true, class: "form-control" %>
  </div>


  <br />
  
  <div class="form-group">
    <%= f.submit "Save Trip", class: "btn btn-outline-success btn-block" %>
  </div>
<% end %>

app/views/trips/edit.html.erb
<div class="row max-width">
  <div class="col-12 center">
    <h3>Edit your trip</h3>
  </div>
</div>

<div class="row max-width mt-3">
  <div class="col-6 auto-margin">
    <%= render "form" %>
    <br>
    <div  class="links">
        <%= link_to "Cancel", @trip , "class": "btn btn-outline-danger btn-sm btn-block mb-3" %>
    </div>
  </div>
</div>

app/views/trips/new.html.erb
<div class="row max-width">
  <div class="col-12 center">
    <h3>Create a new trip</h3>
  </div>
</div>

<div class="row max-width mt-3">
  <div class="col-6 auto-margin">
    <%= render "form" %>
    <br>
    <div  class="links">
        <%= link_to "Cancel", dashboard_path, "class": "btn btn-outline-danger btn-sm btn-block mb-3" %>
    </div>
  </div>
</div>

app/views/trips/show.html.erb
<div class="row max-width bg-img">
  <div class="col-12 center no-padding">
    <%= image_tag image_path("map-pair.jpg"), alt: "map image", class: "hero-img opacity-secondary" %>
  </div>
</div>

<div class="row max-width">
  <div class="col-12 center">
    <h3 class="bold">Trip Itinerary: <span class="italic"><%= @trip.nickname %></span></h3>
    <small><%= link_to "Edit Trip Details", edit_trip_path %></small>
  </div>
</div>

<div class="row max-width mt-3">
  <div class="col-6 align-right">
    <span class="bold">Cost:</span>
  </div>
  <div class="col-6 align-left">
  $<%= @trip.total_cost %>
  </div>
</div>

<div class="row max-width mt-2">
  <div class="col-6 align-right">
    <span class="bold">Funds Deadline:</span>
  </div>
  <div class="col-6 align-left">
  <%= @trip.funds_deadline.strftime("%m/%d/%Y") %>
  </div>
</div>

<div class="row max-width mt-2">
  <div class="col-6 align-right">
    <span class="bold">Trip Start Date:</span>
  </div>
  <div class="col-6 align-left">
  <%= @trip.trip_start_date.strftime("%m/%d/%Y") %>
  </div>
</div>

<div class="row max-width mt-2">
  <div class="col-6 align-right">
    <span class="bold">Trip End Date:</span>
  </div>
  <div class="col-6 align-left">
  <%= @trip.trip_end_date.strftime("%m/%d/%Y") %>
  </div>
</div>

<div class="row max-width mt-2">
  <div class="col-6 align-right">
    <span class="bold">Travel Group:</span>
  </div>
  <div class="col-6 align-left">
  <% if @trip.group %>
    <%= @trip.group.nickname %>
  <% else %>
    You haven't assigned a group yet
  <% end %>
  </div>
</div>

<br />
<div class="row max-width mt-3">
  <h4 class="max-width center">Itinerary:</h4>
</div>
<div class="row max-width trip-itinerary">
  <div class="row max-width">
    <div class="col-12 center">
      <%= link_to image_tag("add-city.png", alt: "city")+" Add a City", new_trip_itinerary_path(@trip), class: "m-2 link" %>    
    </div>
  </div>

  <div class="col-12">
    <% if @itinerary.nil? %>
      No itinerary exists, please start by adding a city.
    <% else %>
      <% @itinerary.each do |i| %>
        <div class="row itinerary-div">
          <div class="col-6 center">
            <%= i.city.city.titlecase %>, 
            <% if i.city.region == "dc" %>
              <%= i.city.region.upcase %>
            <% else %>
              <%= i.city.region.titlecase %>, 
            <% end %>
            <% if i.city.country == "usa" %>
              <%= i.city.country.upcase %>
            <% else %>
              <%= i.city.country.titlecase %>
            <% end %>
            
            <%= link_to image_tag("edit.png", alt: "edit")+" Edit", edit_trip_itinerary_path(@trip, i) ,class: "m-1 link"%>
          </div>
          <div class="col-6 align-left">
            <%= i.start_date.strftime("%m/%d/%Y") %>
            - 
            <%= i.end_date.strftime("%m/%d/%Y") %>
            
            <%= link_to image_tag("delete.png")+" Delete", trip_itinerary_path(@trip, i), class: "m-1 link danger delete-itinerary ml-5"%><br /><br />       
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

<div class="content-div">
  <div class="row max-width mt-5">
    <div class="col-12 center">
      <% if @trip.group %>
        <h4><%= @trip.group.nickname %> Members</h4>
        <small><%= link_to "Edit Group", @trip.group, class: "link" %></small>
      <% else %>
        <h4>Please assign a group.</h4>
        <small><%= link_to "Edit Trip Details", edit_trip_path, class: "link" %></small>
      <% end %>
      <table class="table table-striped table-hover mt-5 max-width">
        <thead>
          <tr>
            <th scope="col">Member</th>
            <th scope="col">Current Funds</th>
            <th scope="col">Goal</th>
            <th scope="col">Progress</th>
            <th scope="col">Remainder</th>
            <th scope="col"></th>
          </tr>
        </thead>
          <tbody>

        <% if @members %>  
          <% @members.each do |member| %>
          <!-- calculate current member's funds -->
            <div class="group-member member-div">
            <% goal = Goal.find_by(user_id: member.id, trip_id: @trip.id) %>
            

            <tr>
              <th scope="row"><%= member.first_name %> <%= member.last_name %></th>
     
              <% if goal.present? %>  
                <% current = goal.current_amount %>
                <% total = goal.total_goal %>
                <% balance = total - current %>
                <% percent = current.to_f/total * 100 %>
                
                <td>$<%= current %></td>
                <td>$<%= total %></td>
                
                <td>
                  <% if percent < 30 %>
                    <span class="red blink">
                  <% elsif percent >= 30 && percent < 60 %>
                    <span class="orange">
                  <% elsif percent >= 60 && percent < 90 %>
                    <span class="yellow">
                  <% elsif percent >= 90 %>
                    <span class="green">
                  <% end %>
                      <%= percent.round(2) %>%
                    </span>
                </td>
                
                <td>
                  <% if balance > 1 %>
                    $<%= balance %>
                  <% elsif balance == 0  %>
                    <span class="green">COMPLETE!</span>
                  <% end %>          
                </td>
              <% else %>
                <td colspan="4"><span class="warning blink">No Goal Set!</span></td>
              <% end %>

              <td> 
                <% if member.id == current_user.id %>
                  <% if goal.present? %>
                    <%= link_to "Edit Goal", edit_goal_path(goal), class: "btn btn-sm btn-info" %>
                  <% else %>
                    <%= link_to "Add Goal", new_trip_goal_path(@trip), class: "btn btn-sm btn-info" %>
                  <% end %>
                <% else %>
                  <%= link_to "Message", @trip, class: "btn btn-outline-info btn-sm message" %>
                <% end %>
              </td>
            </tr>

          </div>

          <% end %>

        <% else %>
          There are no members in this group!
        <% end %>

        </tbody>
      </table>
    </div>
  </div>
</div>