config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # , controllers: {
  # registrations: 'users/registrations',
  # checking if user signs up
  # sessions: 'users/sessions'
  # checking if user is logged into a session
  # }

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "home#index"

  resources :trips do
    resources :groups, only: [:new, :create]
    resources :goals, only: [:new, :create]
    resources :itineraries do
      resources :cities, only: [:new, :create]
    end
  end
  
  resources :groups do
    resources :group_members, only: [:new, :create]
  end

  resources :group_members
  resources :goals, only: [:edit, :update]
  
  resources :charts, only: [] do
    collection  do
      get 'new_users', to: 'charts#new_users'
      get 'trip_start', to: 'charts#trip_start'
      get 'cities', to: 'charts#cities'
      # get 'new_goals', to: 'charts#new_goals'
    end
  end

  get '/dashboard', to: 'dashboard#index'

end

app/models/group.rb
class Group < ApplicationRecord
  validates :nickname, presence: true
  belongs_to :admin, class_name: 'User'
  belongs_to :creator, class_name: 'User' 
  has_many :group_members
  has_many :trips
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :authenticate_user!
  skip_before_action :verify_authenticity_token, only: [:destroy]
    
  def index
    @groups = Group.all
  end

  def show
    @current_group = Group.find(params[:id])
    current_members = GroupMember.where(group_id: @current_group.id)
    @members = []
    current_members.each do |m|
      @members.push([User.find(m.user_id), m.id])
    end
  end

  def new
    @group = Group.new
  end

  def create
    group = Group.create(group_params.merge(
      creator_id: current_user.id, 
      admin_id: current_user.id)
    )
    GroupMember.create(
      group_id: group.id,
     user_id: current_user.id
     )
    flash[:success] = "Group has been successfully created"
    redirect_to group
  end

  def edit
    @group = Group.find(params[:id])
  end

  def update
    @group = Group.find(params[:id])
    @group.update(group_params)
    redirect_to @group
  end

  def destroy
    Group.destroy(params[:id])
    render json: {status: "success", message: "Group was successfully deleted"}
  end

  private

  def group_params
    params.require(:group).permit(
      :nickname, 
      :creator_id, 
      :admin_id
      )
  end

end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.erb
<%= form_for @group do |f| %>
  <div class="form-group">
    <%= f.label :nickname %>
    <%= f.text_field :nickname, class: "form-control" %>
  
  </div>

  <div>
    Admin: <%= current_user.first_name+" "+current_user.last_name+" (me)" %>
  </div>

  <br />
  
  <div class="form-group">
    <%= f.submit "Save Group", class: "btn btn-outline-success btn-block" %>
  </div>
<% end %>

app/views/groups/edit.html.erb
<div class="row max-width">
  <div class="col-12 center">
    <h3>Edit your group name</h3>
  </div>
</div>

<div class="row max-width mt-3">
  <div class="col-6 auto-margin">
    <%= render "form" %>
    <br>
    <div  class="links">
        <%= link_to "Cancel", @group , "class": "btn btn-outline-danger btn-sm btn-block mb-3" %>
    </div>
  </div>
</div>

app/views/groups/new.html.erb
<div class="row max-width">
  <div class="col-12 center">
    <h3>Create a new travel group</h3>
  </div>
</div>

<div class="row max-width mt-3">
  <div class="col-6 auto-margin">
    <%= render "form" %>
    <br>
    <div  class="links">
        <%= link_to "Cancel", dashboard_path, "class": "btn btn-outline-danger btn-sm btn-block mb-3" %>
    </div>
  </div>
</div>

app/views/groups/show.html.erb
<div class="row max-width bg-img">
  <div class="col-12 center no-padding">
    <%= image_tag image_path("friends-truck.jpg"), alt: "friends image", class: "hero-img opacity-secondary" %>
  </div>
</div>

<div class="row max-width mt-2">
  <div class="col-12 center">
    <h3 class="bold">Travel Group: <span class="italic"><%= @current_group.nickname %></span></h3>
    <small><%= link_to "Edit Group Name", edit_group_path %></small>
  </div>
</div>

<div class="row max-width mt-2">
  <div class="col-6 auto-margin">
    <%= link_to "Add New Member", new_group_group_member_path(@current_group), class: "btn btn-info btn-block" %>
  </div>
</div>

<div class="row max-width mt-5">
  <div class="col-12 center">
    <h4>Group Members</h4>
    <ul class="no-padding">
      <% @members.each do |member| %>
        <li class="group-member member-div">
          <%= member[0].first_name %> <%= member[0].last_name %> <%= link_to "Remove", group_member_path(member[-1]), class: 'delete-member' %>
        </li>
      <% end %>
    </ul>
  </div>
</div>