config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # , controllers: {
  # registrations: 'users/registrations',
  # checking if user signs up
  # sessions: 'users/sessions'
  # checking if user is logged into a session
  # }

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "home#index"

  resources :trips do
    resources :groups, only: [:new, :create]
    resources :goals, only: [:new, :create]
    resources :itineraries do
      resources :cities, only: [:new, :create]
    end
  end
  
  resources :groups do
    resources :group_members, only: [:new, :create]
  end

  resources :group_members
  resources :goals, only: [:edit, :update]
  
  resources :charts, only: [] do
    collection  do
      get 'new_users', to: 'charts#new_users'
      get 'trip_start', to: 'charts#trip_start'
      get 'cities', to: 'charts#cities'
      # get 'new_goals', to: 'charts#new_goals'
    end
  end

  get '/dashboard', to: 'dashboard#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
  before_save :downcase_fields
  validates :city, :region, :country, presence: true
  validates_uniqueness_of :city, :scope => [:region, :country], :case_sensitive => false
  # works for city only, region and country are case sensitive
  # validate :unique_city


  has_many :itineraries

  def downcase_fields
    self.city.downcase!
    self.region.downcase!
    self.country.downcase!
  end

  # def unique_city
  #   if City.find_by(city: :city)
  #     validates_uniqueness_of :region, case_sensitive => false
  #     p 'test'
  #   end
  # end
end

app/models/goal.rb
class Goal < ApplicationRecord
  validates :user_id, :trip_id, :total_goal, :current_amount, :deadline, presence: true
  validates_uniqueness_of :trip_id, scope: :user_id
  belongs_to :trip
end

app/models/group.rb
class Group < ApplicationRecord
  validates :nickname, presence: true
  belongs_to :admin, class_name: 'User'
  belongs_to :creator, class_name: 'User' 
  has_many :group_members
  has_many :trips
end

app/models/group_member.rb
class GroupMember < ApplicationRecord
  validates :group_id, :user_id, presence: true
  validates_uniqueness_of :group_id, scope: :user_id
  belongs_to :group
end

app/models/itinerary.rb
class Itinerary < ApplicationRecord
  validates :start_date, :end_date, presence: true
  validates_uniqueness_of :city_id, scope: :trip_id
  belongs_to :trip
  belongs_to :city
end

app/models/trip.rb
class Trip < ApplicationRecord
  validates :nickname, :total_cost, :funds_deadline, :trip_start_date, :trip_end_date, presence: true
 
  belongs_to :group, optional: true
  belongs_to :creator, class_name: 'User'
  has_many :itineraries
  has_many :goals
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :trips
  has_many :groups
end

app/controllers/charts_controller.rb
class ChartsController < ApplicationController
  def new_users
    render json: User.group_by_day(:created_at).count
  end

  def trip_start
    render json: Trip.group(:trip_start_date).count
  end

  def cities
    cities = City.group(:country).count
    results = {}
    cities.keys.each do |key|
      results[key.titleize] = cities[key]
    end
    render json: results
  end

  def new_goals
    # render json: [
    #   { name: "Current".
    #     data: Goal.group(:current).count
    #   }
    # ]
    
    render json: Goal.group(:goal).count

    # render json: [
    #   {name: "Current", data: Goal.group(:current)},
    #   {name: "Goal", data: Goal.group(:goal)}
    # ]

  end
end

app/controllers/goals_controller.rb
class GoalsController < ApplicationController
  respond_to :html, :json
  
  # custom method for chartkick chart
  def new_goals
    # render json: Goal.group_by_day(:created_at).count
    # render json: Goal.where(user_id: :user_id, trip_id: :trip_id)
  end

  def new
    @trip = Trip.find(params[:trip_id])
    @trip_goal = Goal.new
    @form_resource = [@trip, @trip_goal]
  end

  def create
    trip = Trip.find(params[:trip_id])
    Goal.create(goal_params.merge(
      user_id: current_user.id,
       trip_id: trip.id, 
       deadline: trip.funds_deadline
       ))
    redirect_to trip
  end

  def edit
    @trip_goal = Goal.find(params[:id])
    @form_resource = @trip_goal
    @trip = Trip.find(@trip_goal.trip_id)
  end

  def update
    @trip_goal = Goal.find(params[:id])
    @trip_goal.update(goal_params)
    trip = Trip.find(@trip_goal.trip_id)
    redirect_to trip
  end

  private

  def goal_params
    params.require(:goal).permit(
      :total_goal, 
      :current_amount
      )
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  # def index
  #   @users = User.all
  #   respond_to do |f|
  #     f.html
  #   end
  # end

end

app/controllers/trips_controller.rb
class TripsController < ApplicationController
  before_action :authenticate_user!
  skip_before_action :verify_authenticity_token, only: [:destroy]
  
  def index
    @trips = Trip.all
  end

  def new
    @trip = Trip.new
    myGroup = GroupMember.where(user_id: current_user.id)
    @groups = myGroup.map do |g|
      [g.group.nickname, g.group.id]
    end
  end

  def create
    trip = Trip.create(trip_params.merge(creator_id: current_user.id))
    flash[:success] = "Trip has been successfully created"
    redirect_to dashboard_path
  end

  def show
    @trip = Trip.find(params[:id])
    find_trip = Itinerary.where(trip_id: @trip.id)
    @itinerary = []
    if find_trip
      find_trip.each do |t|
        @city = City.find(t.city_id)
        @itinerary.push(t)
      end
    end
    @members = []
    if @trip.group_id
      current_group = Group.find(@trip.group.id)
      current_members = GroupMember.where(group_id: current_group.id)
      current_members.each do |member|
        @members.push(User.find(member.user_id))
      end
    end
  end

  def edit
    @trip = Trip.find(params[:id])
    myGroup = GroupMember.where(user_id: current_user.id)
    @groups = myGroup.map do |g|
      [g.group.nickname,g.group.id]
    end
  end

  def update
    trip = Trip.find(params[:id])
    if trip.group_id != params[:group_id]
      trip.goals.ids.each do |t|
        Goal.destroy(t)
      end
    end
    trip.update(trip_params)
    redirect_to trip
  end

  def destroy
    Trip.destroy(params[:id])
    render json: {
      status: "success",
     message: "Trip was successfully deleted"
   }
  end

  private

  def trip_params
    params.require(:trip).permit(
      :nickname, 
      :total_cost, 
      :funds_deadline, 
      :trip_start_date, 
      :trip_end_date, 
      :group_id
    )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def custom_bootstrap_flash
    flash_messages = []
    flash.each do |type, message|
      type = 'success' if type == 'notice'
      type = 'error'   if type == 'alert'
      text = "<script>toastr.#{type}('#{message}');</script>"
      flash_messages << text.html_safe if message
    end
    flash_messages.join("\n").html_safe
  end
end

app/helpers/charts_helper.rb
module ChartsHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/goals_helper.rb
module GoalsHelper
end

app/helpers/group_members_helper.rb
module GroupMembersHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/itineraries_helper.rb
module ItinerariesHelper
end

app/helpers/trips_helper.rb
module TripsHelper
end

app/views/home/index.html.erb
<div class="row">
  <div class="col-12">
    <h2 class="center welcome-txt animated infinite bounce">
      <% if current_user %>
        Welcome back, <%= current_user.first_name %>!
      <% #unless current_user %>
      <% else %>
        Welcome to the Travel Pals app!
      <% end %>  
    </h2>
  </div>
</div>

<div class="row center">
  <div class="col-12">
    <%= image_tag image_path("friends-cheer.jpg"), alt: "friends image", class: "hero-img opacity-primary" %>
  </div>
</div>

<div class="row mt-2">
  <div class="col-12">
    <h2 id="about" mt-2>About Us</h2>
    <p>Plan and manage your next trip itinerary and fund goals with our easy to use app! Invite friends to your trips and keep track of each others' goals!</p>
    <ul>
      <li>Easy to use</li>
      <li>Create trips</li>
      <li>Add itineraries</li>
      <li>Create groups</li>
      <li>Add friends</li>
      <li>Track trip funds for each member</li>
      <li>Message trip members</li>
    </ul>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quaerat porro, ipsum inventore neque tempore voluptatem architecto, delectus, consequatur iure molestiae impedit. Quibusdam necessitatibus, non quidem vel officiis architecto at natus debitis accusamus. Quibusdam maxime explicabo asperiores recusandae laboriosam quam laborum deserunt cum voluptatum enim at eum quaerat omnis adipisci maiores quo necessitatibus culpa cupiditate, corporis. Quaerat minus voluptatem illum, temporibus nostrum, cupiditate possimus facere optio quisquam necessitatibus dolor commodi, maxime, nihil! Quis voluptatem dolorum praesentium magni dicta ea modi quia, odit placeat suscipit in repellendus fugiat pariatur, excepturi culpa, earum laudantium, accusantium. Quibusdam corporis autem placeat libero obcaecati, dolor tempore at delectus, impedit vero magnam odit, porro ad eos minus labore quaerat. Incidunt architecto repellat vel officiis est laborum optio modi ipsam, tempora perferendis sequi quasi, praesentium atque. Temporibus suscipit nam consectetur autem molestias corrupti inventore quia quaerat modi perferendis nobis beatae eos numquam excepturi nihil nisi sequi debitis, placeat, at provident deleniti quas optio minima dicta. Quae illo, numquam quasi rerum nesciunt voluptate velit aperiam eius. Nihil provident alias optio eveniet autem quam necessitatibus, debitis sed aspernatur similique quia suscipit maiores neque qui officiis id dolore assumenda asperiores. Cum facere, voluptatem quasi. Qui itaque deserunt, soluta excepturi quasi ex.</p>
  </div>
</div>

<div class="row mt-4 mb-4">
  <div class="col-12 center">
    <h4 class="bold-3rd">Look at our users' upcoming travel dates!</h4><br />
    <%= line_chart trip_start_charts_path, messages: {empty: "No data"} %>
  </div>
</div>

<div class="row mt-4 mb-4">
  <div class="col-12 center">
    <h4 class="bold-3rd">See which countries our users are visiting!</h4><br />
    <%= pie_chart cities_charts_path, legend: "bottom", messages: {empty: "No data"} %>
  </div>
</div>